imports:
    - { resource: config.yml }

#doctrine:
#    orm:
#        metadata_cache_driver: apc
#        result_cache_driver: apc
#        query_cache_driver: apc
#doctrine:
#    dbal:
#        url: "%env(DATABASE_URL)%"

monolog:
    # ...
    handlers:
        # ...
        nested:
            type: stream
            path: 'php://stderr'